name: biox7002-rnaseq
channels:
  - conda-forge
  - bioconda
dependencies:
  - fastqc=0.11.9
  - multiqc=1.14
  - fastp=0.23.2
  - bowtie2=2.4.5
  - salmon=1.9.0
  - pigz
  - python=3.11
  - r-base=4.3
  - r-essentials
